#!/usr/bin/env python3
"""
Extract a lightweight, LLM-friendly source view of a Jupyter notebook.

WHY THIS EXISTS
---------------
Johnston_St_v2.ipynb is ~6.3MB because every cell carries embedded image outputs
(base64 PNGs from matplotlib/folium). Feeding that raw file to an LLM/coding-agent
exhausts its context window and stalls the session — this actually happened during
the 260711-gif quick task (a plan-checker agent hung on the raw notebook).

This script strips all outputs and emits ONLY the code + markdown source of each
cell, tagged with its 0-based index. The result (~250KB) is small enough for an
agent to read comfortably, while preserving exact cell indices so NotebookEdit
calls line up.

USAGE
-----
    python scripts/extract_notebook_source.py                 # default notebook
    python scripts/extract_notebook_source.py MyNotebook.ipynb OUT.txt

Regenerate the snapshot AFTER editing the notebook so the extract stays in sync.
The committed snapshot lives at: Johnston_St_v2_source.txt
"""
import json
import sys
from pathlib import Path

DEFAULT_NB = "Johnston_St_v2.ipynb"
DEFAULT_OUT = "Johnston_St_v2_source.txt"


def extract(nb_path: Path, out_path: Path) -> int:
    nb = json.loads(nb_path.read_text(encoding="utf-8"))
    cells = nb["cells"]
    lines = [
        f"# Lightweight source extract of {nb_path.name} — code/markdown ONLY, no outputs.",
        "# Generated by scripts/extract_notebook_source.py. Regenerate after editing the notebook.",
        "# 0-based cell indices match the .ipynb — safe to reference in NotebookEdit.",
        f"# Total cells: {len(cells)}",
        "",
    ]
    for i, c in enumerate(cells):
        kind = "MD" if c["cell_type"] == "markdown" else "CODE"
        lines.append(f"# ================= CELL {i:03d} [{kind}] =================")
        lines.append("".join(c["source"]))
        lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")
    return len(cells)


if __name__ == "__main__":
    root = Path(__file__).resolve().parent.parent
    nb = Path(sys.argv[1]) if len(sys.argv) > 1 else root / DEFAULT_NB
    out = Path(sys.argv[2]) if len(sys.argv) > 2 else root / DEFAULT_OUT
    n = extract(nb, out)
    print(f"[extract] {nb.name}: {n} cells -> {out} ({out.stat().st_size:,} bytes)")
